const Subgenres: { [key: string]: string } = {
    //Alternative
    'adult alternative pop/rock': 'KZazBEonSMnZfZ7vAvE',
    'alternative dance': 'KZazBEonSMnZfZ7vAvI',
    'alternative metal': 'KZazBEonSMnZfZ7vAvt',
    'alternative rock': 'KZazBEonSMnZfZ7vAvn',
    'ambient pop': 'KZazBEonSMnZfZ7vAvl',
    'american alternative': 'KZazBEonSMnZfZ7vAev',
    'americana': 'KZazBEonSMnZfZ7vAee',
    'baroque pop': 'KZazBEonSMnZfZ7vAed',
    'british alternative': 'KZazBEonSMnZfZ7vAe7',
    'british ska': 'KZazBEonSMnZfZ7vAeA',
    'c-86': 'KZazBEonSMnZfZ7vAek',
    'chamber pop': 'KZazBEonSMnZfZ7vAe6',
    'cocktail': 'KZazBEonSMnZfZ7vAeF',
    'college rock': 'KZazBEonSMnZfZ7vAea',
    'cowpunk': 'KZazBEonSMnZfZ7vAe1',
    'dream pop': 'KZazBEonSMnZfZ7vAeJ',
    'electro-industrial': 'KZazBEonSMnZfZ7vAeE',
    'electronic pop': 'KZazBEonSMnZfZ7vAeI',
    'funk metal': 'KZazBEonSMnZfZ7vAet',
    'goth': 'KZazBEonSMnZfZ7vAen',
    'grunge': 'KZazBEonSMnZfZ7vAel',
    'indie pop': 'KZazBEonSMnZfZ7vAdv',
    'indie rock': 'KZazBEonSMnZfZ7vAde',
    'industrial': 'KZazBEonSMnZfZ7vAdd',
    'industrial dance': 'KZazBEonSMnZfZ7vAd7',
    'jangle pop': 'KZazBEonSMnZfZ7vAdA',
    'lo-fi': 'KZazBEonSMnZfZ7vAdk',
    'madchester': 'KZazBEonSMnZfZ7vAd6',
    'math rock': 'KZazBEonSMnZfZ7vAdF',
    'neo-glam': 'KZazBEonSMnZfZ7vAda',
    'neo-psychedelia': 'KZazBEonSMnZfZ7vAd1',
    'neo-traditional folk': 'KZazBEonSMnZfZ7vAdJ',
    'new zealand rock': 'KZazBEonSMnZfZ7vAdE',
    'noise pop': 'KZazBEonSMnZfZ7vAdI',
    'paisley underground': 'KZazBEonSMnZfZ7vAdt',
    'pop underground': 'KZazBEonSMnZfZ7vAdn',
    'post-grunge': 'KZazBEonSMnZfZ7vAdl',
    'post-punk': 'KZazBEonSMnZfZ7vA7v',
    'post-punk revival': 'KZazBEonSMnZfZ7vA7e',
    'post-rock/experimental': 'KZazBEonSMnZfZ7vA7d',
    'psychobilly': 'KZazBEonSMnZfZ7vA77',
    'queercore': 'KZazBEonSMnZfZ7vA7A',
    'riot grrrl': 'KZazBEonSMnZfZ7vA7k',
    'sadcore': 'KZazBEonSMnZfZ7vA76',
    'shoegaze': 'KZazBEonSMnZfZ7vA7F',
    'ska punk': 'KZazBEonSMnZfZ7vA71',
    'skatepunk': 'KZazBEonSMnZfZ7vA7J',
    'slowcore': 'KZazBEonSMnZfZ7vA7E',
    'space rock': 'KZazBEonSMnZfZ7vA7I',
    'third wave ska revival': 'KZazBEonSMnZfZ7vA7t',
    'twee pop': 'KZazBEonSMnZfZ7vA7n',
    'urban folk': 'KZazBEonSMnZfZ7vA7l',
    // blues
    'ballads/romantic': 'KnvZfZ7vAve',
    'acoustic blues': 'KZazBEonSMnZfZ7vAA7',
    'avant-garde blues': 'KZazBEonSMnZfZ7vAAA',
    'blues': 'KZazBEonSMnZfZ7vAAd',
    'blues gospel': 'KZazBEonSMnZfZ7vAAk',
    'blues revival': 'KZazBEonSMnZfZ7vAA6',
    'british blues': 'KZazBEonSMnZfZ7vAF7',
    'chicago blues': 'KZazBEonSMnZfZ7vAAF',
    'contemporary blues': 'KZazBEonSMnZfZ7vAAa',
    'country blues': 'KZazBEonSMnZfZ7vAA1',
    'delta blues': 'KZazBEonSMnZfZ7vAAE',
    'detroit blues': 'KZazBEonSMnZfZ7vAAI',
    'dirty blues': 'KZazBEonSMnZfZ7vAAt',
    'early american blues': 'KZazBEonSMnZfZ7vAAn',
    'east coast blues': 'KZazBEonSMnZfZ7vAAl',
    'electric blues': 'KZazBEonSMnZfZ7vAkv',
    'electric blues guitar': 'KZazBEonSMnZfZ7vAke',
    'electric harmonica blues': 'KZazBEonSMnZfZ7vAkd',
    'finger-picked guitar': 'KZazBEonSMnZfZ7vAk7',
    'folk-blues': 'KZazBEonSMnZfZ7vAkA',
    'harmonica blues': 'KZazBEonSMnZfZ7vAkk',
    'jazz blues': 'KZazBEonSMnZfZ7vAk6',
    'juke joint blues': 'KZazBEonSMnZfZ7vAkF',
    'jump blues': 'KZazBEonSMnZfZ7vAka',
    'louisiana blues': 'KZazBEonSMnZfZ7vAk1',
    'memphis blues': 'KZazBEonSMnZfZ7vAkJ',
    'modern blues': 'KZazBEonSMnZfZ7vAkE',
    'modern delta blues': 'KZazBEonSMnZfZ7vAkI',
    'modern electric blues': 'KZazBEonSMnZfZ7vAkt',
    'modern electric chicago blues': 'KZazBEonSMnZfZ7vAkn',
    'modern electric d618': 'KZazBEonSMnZfZ7vav7',
    'modern electric texas blues': 'KZazBEonSMnZfZ7vAkl',
    'new orleans blues': 'KZazBEonSMnZfZ7vA6v',
    'new york blues': 'KZazBEonSMnZfZ7vA6e',
    'piano blues': 'KZazBEonSMnZfZ7vA6d',
    'piedmont blues': 'KZazBEonSMnZfZ7vA67',
    'prewar blues': 'KZazBEonSMnZfZ7vA6A',
    'prewar-country blues': 'KZazBEonSMnZfZ7vA6F',
    'prewar-gospel blues': 'KZazBEonSMnZfZ7vA6a',
    'slide guitar': 'KZazBEonSMnZfZ7vA61',
    'soul-blues': 'KZazBEonSMnZfZ7vA6J',
    'st. louis blues': 'KZazBEonSMnZfZ7vA6E',
    'swamp blues': 'KZazBEonSMnZfZ7vA6I',
    'texas blues': 'KZazBEonSMnZfZ7vA6t',
    'traditional blues': 'KZazBEonSMnZfZ7vA6n',
    'vaudeville blues': 'KZazBEonSMnZfZ7vA6l',
    'vocal blues': 'KZazBEonSMnZfZ7vAFv',
    'west coast blues': 'KZazBEonSMnZfZ7vAFe',
    //Misc
    'chanson francaise': 'KZazBEonSMnZfZ7vAFk',
    "children's music": 'KZazBEonSMnZfZ7vAFF',
    'classical': 'KZazBEonSMnZfZ7vaad',
    'church music': 'KZazBEonSMnZfZ7vF1A',
    'classical/vocal': 'KZazBEonSMnZfZ7vF1A',
    'alternative country': 'KZazBEonSMnZfZ7vAF1',
    'avant-garde country': 'KZazBEonSMnZfZ7vAFJ',
    'bakersfield sound': 'KZazBEonSMnZfZ7vAFE',
    'bluegrass': 'KZazBEonSMnZfZ7vAFI',
    'bluegrass-gospel': 'KZazBEonSMnZfZ7vAFt',
    'classic country': 'KZazBEonSMnZfZ7vAFn',
    'close harmony': 'KZazBEonSMnZfZ7vAFl',
    'contemporary bluegrass': 'KZazBEonSMnZfZ7vAav',
    'contemporary country': 'KZazBEonSMnZfZ7vAae',
    'country': 'KZazBEonSMnZfZ7vAFa',
    'country folk': 'KZazBEonSMnZfZ7vAad',
    'country gospel': 'KZazBEonSMnZfZ7vAa7',
    'country pop': 'KZazBEonSMnZfZ7vAaA',
    'country soul': 'KZazBEonSMnZfZ7vAak',
    'cowboy': 'KZazBEonSMnZfZ7vAa6',
    'honky tonk': 'KZazBEonSMnZfZ7vAaF',
    'instrumental': 'KZazBEonSMnZfZ7vAaa',
    'jug band': 'KZazBEonSMnZfZ7vAa1',
    'nashville sound': 'KZazBEonSMnZfZ7vAaJ',
    'neo-traditional country': 'KZazBEonSMnZfZ7vAaE',
    'old-time country': 'KZazBEonSMnZfZ7vAaI',
    'outlaw country': 'KZazBEonSMnZfZ7vAat',
    'progressive country': 'KZazBEonSMnZfZ7vAan',
    'roadhouse country': 'KZazBEonSMnZfZ7vAal',
    'songster': 'KZazBEonSMnZfZ7vA1v',
    'square dance': 'KZazBEonSMnZfZ7vA1e',
    'string dance': 'KZazBEonSMnZfZ7vA1d',
    'traditional bluegrass': 'KZazBEonSMnZfZ7vA17',
    'traditional country': 'KZazBEonSMnZfZ7vA1A',
    'truck driving country': 'KZazBEonSMnZfZ7vA1k',
    'urban cowboy': 'KZazBEonSMnZfZ7vA16',
    'western swing & country boogie': 'KZazBEonSMnZfZ7vA1F',
    'western swing revival': 'KZazBEonSMnZfZ7vA1a',
    'work songs': 'KZazBEonSMnZfZ7vA11',
    'yodeling': 'KZazBEonSMnZfZ7vA1J',
    '2-step': 'KZazBEonSMnZfZ7vA1I',
    '2-step/british garage': 'KZazBEonSMnZfZ7vA1t',
    'acid house': 'KZazBEonSMnZfZ7vA1n',
    'acid jazz': 'KZazBEonSMnZfZ7vA1l',
    'acid techno': 'KZazBEonSMnZfZ7vAJv',
    'ambient': 'KZazBEonSMnZfZ7vAJe',
    'ambient breakbeat': 'KZazBEonSMnZfZ7vAJd',
    'ambient electronica': 'KZazBEonSMnZfZ7vAJ7',
    'ambient house': 'KZazBEonSMnZfZ7vAJA',
    'ambient techno': 'KZazBEonSMnZfZ7vAJk',
    'avant-garde': 'KZazBEonSMnZfZ7vAJ6',
    'big beat': 'KZazBEonSMnZfZ7vAJF',
    'broken beat': 'KZazBEonSMnZfZ7vAJa',
    'chillwave': 'KZazBEonSMnZfZ7vaan',
    'club dance': 'KZazBEonSMnZfZ7vAJ1',
    'dance band': 'KZazBEonSMnZfZ7vaak',
    'dance pop': 'KZazBEonSMnZfZ7vAJJ',
    'dance-rock': 'KZazBEonSMnZfZ7vAJE',
    'dance/electronic': 'KZazBEonSMnZfZ7vA1E',
    'dark ambient': 'KZazBEonSMnZfZ7vAJI',
    'detroit techno': 'KZazBEonSMnZfZ7vAJt',
    'disco': 'KZazBEonSMnZfZ7vAJn',
    'disco polo': 'KZazBEonSMnZfZ7vaa6',
    'downbeat': 'KZazBEonSMnZfZ7vAJl',
    'downtempo': 'KZazBEonSMnZfZ7vAEv',
    'drill\'n\'bass': 'KZazBEonSMnZfZ7vAEe',
    'drum \'n\' bass': 'KZazBEonSMnZfZ7vAEd',
    'dub electronica': 'KZazBEonSMnZfZ7vAE7',
    'dubstep': 'KZazBEonSMnZfZ7vaal',
    'electro-jazz': 'KZazBEonSMnZfZ7vAEA',
    'electro-techno': 'KZazBEonSMnZfZ7vAEk',
    'electronica mainstream': 'KZazBEonSMnZfZ7vAE6',
    'euro-dance': 'KZazBEonSMnZfZ7vAEF',
    'experimental': 'KZazBEonSMnZfZ7va1v',
    'experimental ambient': 'KZazBEonSMnZfZ7vAEa',
    'experimental dub': 'KZazBEonSMnZfZ7vAE1',
    'experimental electro': 'KZazBEonSMnZfZ7vAEJ',
    'experimental jungle': 'KZazBEonSMnZfZ7vAEE',
    'experimental techno': 'KZazBEonSMnZfZ7vAEI',
    'freestyle': 'KZazBEonSMnZfZ7vAEt',
    'funky breaks': 'KZazBEonSMnZfZ7vAEn',
    'gabba': 'KZazBEonSMnZfZ7vAEl',
    'glitch': 'KZazBEonSMnZfZ7vAIv',
    'goa trance': 'KZazBEonSMnZfZ7vAIe',
    'grime': 'KZazBEonSMnZfZ7vAId',
    'happy hardcore': 'KZazBEonSMnZfZ7vAI7',
    'hardcore techno': 'KZazBEonSMnZfZ7vAIA',
    'hi-nrg': 'KZazBEonSMnZfZ7vAIk',
    'house': 'KZazBEonSMnZfZ7vAI6',
    'illbient': 'KZazBEonSMnZfZ7vAIF',
    'industrial drum\'n\'bass': 'KZazBEonSMnZfZ7vAIa',
    'intelligent dance music': 'KZazBEonSMnZfZ7vAI1',
    'jazz-house': 'KZazBEonSMnZfZ7vAIJ',
    'jungle/drum \'n\' bass': 'KZazBEonSMnZfZ7vAIE',
    'latin electronica': 'KZazBEonSMnZfZ7vAII',
    'left-field house': 'KZazBEonSMnZfZ7vAIt',
    'microhouse': 'KZazBEonSMnZfZ7vAIn',
    'microsound': 'KZazBEonSMnZfZ7vAIl',
    'minimal techno': 'KZazBEonSMnZfZ7vAtv',
    'neo-electro': 'KZazBEonSMnZfZ7vAte',
    'newbeat': 'KZazBEonSMnZfZ7vAtd',
    'nu breaks': 'KZazBEonSMnZfZ7vAt7',
    'post-disco': 'KZazBEonSMnZfZ7vAtA',
    'progressive house': 'KZazBEonSMnZfZ7vAtk',
    'progressive trance': 'KZazBEonSMnZfZ7vAt6',
    'rave': 'KZazBEonSMnZfZ7vAtF',
    'synthwave': 'KZazBEonSMnZfZ7va1e',
    'tech-house': 'KZazBEonSMnZfZ7vAta',
    'techno': 'KZazBEonSMnZfZ7vAt1',
    'techno bass': 'KZazBEonSMnZfZ7vAtJ',
    'techno-dub': 'KZazBEonSMnZfZ7vAtE',
    'techno-house': 'KZazBEonSMnZfZ7vAtI',
    'trance': 'KZazBEonSMnZfZ7vAtt',
    'trap': 'KZazBEonSMnZfZ7va1d',
    'tribal-house': 'KZazBEonSMnZfZ7vAtn',
    'trip hop': 'KZazBEonSMnZfZ7vAtl',
    'turntablists': 'KZazBEonSMnZfZ7vAnv',
    'u.k. garage': 'KZazBEonSMnZfZ7vAne',
    'vaporwave': 'KZazBEonSMnZfZ7va17',
    'witch house': 'KZazBEonSMnZfZ7va1A',
    'witchstep': 'KZazBEonSMnZfZ7va1k',
    'world dance': 'KZazBEonSMnZfZ7vAnd','a cappella': 'KZazBEonSMnZfZ7vAnA',
    'acadian': 'KZazBEonSMnZfZ7vAnk',
    'acid folk': 'KZazBEonSMnZfZ7vAn6',
    'alternative folk': 'KZazBEonSMnZfZ7vAnF',
    'andean folk': 'KZazBEonSMnZfZ7vAn1',
    'anti-folk': 'KZazBEonSMnZfZ7vAnJ',
    'appalachian folk': 'KZazBEonSMnZfZ7vAnE',
    'british folk': 'KZazBEonSMnZfZ7vAnI',
    'bulgarian folk': 'KZazBEonSMnZfZ7vAnt',
    'celtic folk': 'KZazBEonSMnZfZ7vAnn',
    'central european folk': 'KZazBEonSMnZfZ7vAnl',
    'contemporary folk': 'KZazBEonSMnZfZ7vAlv',
    'creole': 'KZazBEonSMnZfZ7vAle',
    'field recordings': 'KZazBEonSMnZfZ7vAld',
    'folk': 'KZazBEonSMnZfZ7vAn7',
    'folk jazz': 'KZazBEonSMnZfZ7vAl7',
    'folk punk': 'KZazBEonSMnZfZ7va16',
    'folk revival': 'KZazBEonSMnZfZ7vAlA',
    'folk rock': 'KZazBEonSMnZfZ7vAlk',
    'folksongs': 'KZazBEonSMnZfZ7vAlF',
    'german folk': 'KZazBEonSMnZfZ7vaa7',
    'greek folk': 'KZazBEonSMnZfZ7vAla',
    'hungarian folk': 'KZazBEonSMnZfZ7vAl1',
    'indie folk': 'KZazBEonSMnZfZ7va1F',
    'irish folk': 'KZazBEonSMnZfZ7vAlJ',
    'jewish folk': 'KZazBEonSMnZfZ7vAlE',
    'klezmer': 'KZazBEonSMnZfZ7vAlI',
    'latin america': 'KZazBEonSMnZfZ7vAlt',
    'latin folk': 'KZazBEonSMnZfZ7vAln',
    'mediterranean': 'KZazBEonSMnZfZ7vAll',
    'mexican folk': 'KZazBEonSMnZfZ7vkvv',
    'middle eastern': 'KZazBEonSMnZfZ7vkve',
    'new acoustic': 'KZazBEonSMnZfZ7vkv7',
    'political folk': 'KZazBEonSMnZfZ7vkvA',
    'revival': 'KZazBEonSMnZfZ7vkvk',
    'schlager & volksmusik': 'KZazBEonSMnZfZ7vaaF',
    'scottish folk': 'KZazBEonSMnZfZ7vkv6',
    'sea shanties': 'KZazBEonSMnZfZ7vkvF',
    'traditional cajun': 'KZazBEonSMnZfZ7vkva',
    'traditional folk': 'KZazBEonSMnZfZ7vkv1',
    'traditional irish folk': 'KZazBEonSMnZfZ7vkvJ',
    'traditional middle eastern folk': 'KZazBEonSMnZfZ7vkvE',
    'traditional scottish folk': 'KZazBEonSMnZfZ7vkvI',
    'zydeco': 'KZazBEonSMnZfZ7vkvn',
    //rap
    'Hip-Hop/Rap': 'KZazBEonSMnZfZ7vkvl',
    'Alternative Rap': 'KZazBEonSMnZfZ7vkev',
    'British Rap': 'KZazBEonSMnZfZ7vkee',
    'Christian Rap': 'KZazBEonSMnZfZ7vked',
    'Dirty Rap': 'KZazBEonSMnZfZ7vke7',
    'East Coast Rap': 'KZazBEonSMnZfZ7vkeA',
    'Electro': 'KZazBEonSMnZfZ7vkek',
    'French Rap': 'KZazBEonSMnZfZ7vaa1',
    'Gangsta Rap': 'KZazBEonSMnZfZ7vke6',
    'Hardcore Rap': 'KZazBEonSMnZfZ7vkeF',
    'Jazz-Rap': 'KZazBEonSMnZfZ7vkea',
    'Latin Hip-Hop': 'KZazBEonSMnZfZ7vke1',
    'Latin Rap': 'KZazBEonSMnZfZ7vkeJ',
    'Midwestern Rap': 'KZazBEonSMnZfZ7vkeE',
    'Old School Rap': 'KZazBEonSMnZfZ7vkeI',
    'Party Rap': 'KZazBEonSMnZfZ7vket',
    'Political Rap': 'KZazBEonSMnZfZ7vken',
    'Rap-Rock': 'KZazBEonSMnZfZ7vkel',
    'Reggaeton': 'KZazBEonSMnZfZ7vkdv',
    'Southern Rap': 'KZazBEonSMnZfZ7vkde',
    'Turntablism': 'KZazBEonSMnZfZ7vkdd',
    'Underground Rap': 'KZazBEonSMnZfZ7vkd7',
    'Urban': 'KZazBEonSMnZfZ7vkdA',
    'West Coast Rap': 'KZazBEonSMnZfZ7vkdk',
    //Jazz
    'Christmas Music': 'KZazBEonSMnZfZ7vkdF',
    'Holiday': 'KZazBEonSMnZfZ7vkd6',
    'Acid Jazz': 'KZazBEonSMnZfZ7vkd1',
    'African Jazz': 'KZazBEonSMnZfZ7vkdJ',
    'Afro-Cuban Jazz': 'KZazBEonSMnZfZ7vkdE',
    'Avant-Garde Jazz': 'KZazBEonSMnZfZ7vkdI',
    'Ballads': 'KZazBEonSMnZfZ7vkdt',
    'Ballroom Dance': 'KZazBEonSMnZfZ7vkdn',
    'Bebop': 'KZazBEonSMnZfZ7vkdl',
    'Big Band': 'KZazBEonSMnZfZ7vk7v',
    'Big Band/Swing': 'KZazBEonSMnZfZ7vk7e',
    'Boogie-Woogie': 'KZazBEonSMnZfZ7vk7d',
    'Brazilian Jazz': 'KZazBEonSMnZfZ7vk77',
    'British Dance Bands': 'KZazBEonSMnZfZ7vk7A',
    'Classic Big Band': 'KZazBEonSMnZfZ7vk7k',
    'Classic Jazz': 'KZazBEonSMnZfZ7vk76',
    'Contemporary Big Band': 'KZazBEonSMnZfZ7vk7F',
    'Contemporary Jazz': 'KZazBEonSMnZfZ7vk7a',
    'Continental Jazz': 'KZazBEonSMnZfZ7vk71',
    'Cool': 'KZazBEonSMnZfZ7vk7J',
    'Cool Jazz': 'KZazBEonSMnZfZ7vk7E',
    'Crossover Jazz': 'KZazBEonSMnZfZ7vk7I',
    'Cuban Big Band': 'KZazBEonSMnZfZ7vk7t',
    'Cuban Jazz': 'KZazBEonSMnZfZ7vk7n',
    'Dance Bands': 'KZazBEonSMnZfZ7vk7l',
    'Dixieland': 'KZazBEonSMnZfZ7vkAv',
    'Early Creative': 'KZazBEonSMnZfZ7vkAe',
    'European Jazz': 'KZazBEonSMnZfZ7vkAd',
    'Experimental Big Band': 'KZazBEonSMnZfZ7vkA7',
    'Free Funk': 'KZazBEonSMnZfZ7vkAA',
    'Free Jazz': 'KZazBEonSMnZfZ7vkAk',
    'Fusion': 'KZazBEonSMnZfZ7vkA6',
    'Hard Bop': 'KZazBEonSMnZfZ7vkAF',
    'Jazz': 'KZazBEonSMnZfZ7vkda',
    'Jazz Funk': 'KZazBEonSMnZfZ7vkAa',
    'Jazz Standards': 'KZazBEonSMnZfZ7vkA1',
    'Jive': 'KZazBEonSMnZfZ7vkAJ',
    'Jive Jazz': 'KZazBEonSMnZfZ7vkAE',
    'Latin Jazz': 'KZazBEonSMnZfZ7vkAI',
    'M-Base': 'KZazBEonSMnZfZ7vkAt',
    'Modern Big Band': 'KZazBEonSMnZfZ7vkAn',
    'Modern Creative': 'KZazBEonSMnZfZ7vkAl',
    'Modern Free': 'KZazBEonSMnZfZ7vkkv',
    'New Orleans Brass Bands': 'KZazBEonSMnZfZ7vkke',
    'New Orleans Jazz': 'KZazBEonSMnZfZ7vkkd',
    'Novelty Ragtime': 'KZazBEonSMnZfZ7vkk7',
    'Orchestral Jazz': 'KZazBEonSMnZfZ7vkkA',
    'Post-Bop': 'KZazBEonSMnZfZ7vkkk',
    'Progressive Big Band': 'KZazBEonSMnZfZ7vkk6',
    'Progressive Jazz': 'KZazBEonSMnZfZ7vkkF',
    'Ragtime': 'KZazBEonSMnZfZ7vkka',
    'Retro Swing': 'KZazBEonSMnZfZ7vkk1',
    'Smooth Jazz': 'KZazBEonSMnZfZ7vkkJ',
    'Society Dance Band': 'KZazBEonSMnZfZ7vkkE',
    'Soul Jazz': 'KZazBEonSMnZfZ7vkkI',
    'Soul-Jazz & Boogaloo': 'KZazBEonSMnZfZ7vkkt',
    'Stride Piano': 'KZazBEonSMnZfZ7vkkn',
    'Sweet Bands': 'KZazBEonSMnZfZ7vkkl',
    'Swing': 'KZazBEonSMnZfZ7vk6v',
    'Swing Jazz': 'KZazBEonSMnZfZ7vk6e',
    'Third Stream': 'KZazBEonSMnZfZ7vk6d',
    'Traditional Jazz & Ragtime': 'KZazBEonSMnZfZ7vk67',
    'Vintage Dance Bands': 'KZazBEonSMnZfZ7vk6A',
    'Vocal Jazz': 'KZazBEonSMnZfZ7vk6k',
    'Vocalese': 'KZazBEonSMnZfZ7vk66',
    'West Coast Jazz': 'KZazBEonSMnZfZ7vk6F',
    'World Jazz': 'KZazBEonSMnZfZ7vk6a',
    'Latin': 'KZazBEonSMnZfZ7va1a',
    'Latin Children\'s': 'KZazBEonSMnZfZ7va11',
    'Latin Christian': 'KZazBEonSMnZfZ7va1J',
    'Latin Contemporary Christian': 'KZazBEonSMnZfZ7va1E',
    'Latin Dance': 'KZazBEonSMnZfZ7va1I',
    'Latin Electronica': 'KZazBEonSMnZfZ7va1t',
    'Latin Folk': 'KZazBEonSMnZfZ7va1n',
    'Latin Freestyle': 'KZazBEonSMnZfZ7va1l',
    'Latin Soul': 'KZazBEonSMnZfZ7vaJA',
    'Latin Pop': 'KZazBEonSMnZfZ7vaJd',
    'Latin Rock': 'KZazBEonSMnZfZ7vaJ7',
    'Medieval/Renaissance': 'KZazBEonSMnZfZ7vk61',
    'Middle Age': 'KZazBEonSMnZfZ7vk6J',
    'Christian Metal': 'KZazBEonSMnZfZ7vk6I',
    'Death Metal/Black Metal': 'KZazBEonSMnZfZ7vk6t',
    'Doom Metal': 'KZazBEonSMnZfZ7vk6n',
    'Funk Metal': 'KZazBEonSMnZfZ7vk6l',
    'Goth Metal': 'KZazBEonSMnZfZ7vkFv',
    'Hair Metal': 'KZazBEonSMnZfZ7vkFe',
    'Heavy Metal': 'KZazBEonSMnZfZ7vkFd',
    'Industrial Metal': 'KZazBEonSMnZfZ7vkF7',
    'Metal': 'KZazBEonSMnZfZ7vk6E',
    'Metalcore': 'KZazBEonSMnZfZ7vaJk',
    'Neo-Classical Metal': 'KZazBEonSMnZfZ7vkFA',
    'New Wave Of British Heavy Metal': 'KZazBEonSMnZfZ7vkFk',
    'Nu-Metal': 'KZazBEonSMnZfZ7vaJ6',
    'Pop Metal': 'KZazBEonSMnZfZ7vkF6',
    'Power Metal': 'KZazBEonSMnZfZ7vkFF',
    'Punk Metal': 'KZazBEonSMnZfZ7vkFa',
    'Rap-Metal': 'KZazBEonSMnZfZ7vkF1',
    'Scandinavian Metal': 'KZazBEonSMnZfZ7vkFJ',
    'Sludge Metal': 'KZazBEonSMnZfZ7vkFE',
    'Speed Metal': 'KZazBEonSMnZfZ7vkFI',
    'Stoner Metal': 'KZazBEonSMnZfZ7vkFt',
    'Symphonic Black Metal': 'KZazBEonSMnZfZ7vkFn',
    'Thrash & Speed': 'KZazBEonSMnZfZ7vkFl',
    'New Age': 'KZazBEonSMnZfZ7vkAn'
}

export default Subgenres;