const Subgenres: { [key: string]: string } = {
    'adult alternative pop/rock': 'KZazBEonSMnZfZ7vAvE',
    'alternative dance': 'KZazBEonSMnZfZ7vAvI',
    'alternative metal': 'KZazBEonSMnZfZ7vAvt',
    'alternative rock': 'KZazBEonSMnZfZ7vAvn',
    'ambient pop': 'KZazBEonSMnZfZ7vAvl',
    'american alternative': 'KZazBEonSMnZfZ7vAev',
    'americana': 'KZazBEonSMnZfZ7vAee',
    'baroque pop': 'KZazBEonSMnZfZ7vAed',
    'british alternative': 'KZazBEonSMnZfZ7vAe7',
    'british ska': 'KZazBEonSMnZfZ7vAeA',
    'c-86': 'KZazBEonSMnZfZ7vAek',
    'chamber pop': 'KZazBEonSMnZfZ7vAe6',
    'cocktail': 'KZazBEonSMnZfZ7vAeF',
    'college rock': 'KZazBEonSMnZfZ7vAea',
    'cowpunk': 'KZazBEonSMnZfZ7vAe1',
    'dream pop': 'KZazBEonSMnZfZ7vAeJ',
    'electro-industrial': 'KZazBEonSMnZfZ7vAeE',
    'electronic pop': 'KZazBEonSMnZfZ7vAeI',
    'funk metal': 'KZazBEonSMnZfZ7vAet',
    'goth': 'KZazBEonSMnZfZ7vAen',
    'grunge': 'KZazBEonSMnZfZ7vAel',
    'indie pop': 'KZazBEonSMnZfZ7vAdv',
    'indie rock': 'KZazBEonSMnZfZ7vAde',
    'industrial': 'KZazBEonSMnZfZ7vAdd',
    'industrial dance': 'KZazBEonSMnZfZ7vAd7',
    'jangle pop': 'KZazBEonSMnZfZ7vAdA',
    'lo-fi': 'KZazBEonSMnZfZ7vAdk',
    'madchester': 'KZazBEonSMnZfZ7vAd6',
    'math rock': 'KZazBEonSMnZfZ7vAdF',
    'neo-glam': 'KZazBEonSMnZfZ7vAda',
    'neo-psychedelia': 'KZazBEonSMnZfZ7vAd1',
    'neo-traditional folk': 'KZazBEonSMnZfZ7vAdJ',
    'new zealand rock': 'KZazBEonSMnZfZ7vAdE',
    'noise pop': 'KZazBEonSMnZfZ7vAdI',
    'paisley underground': 'KZazBEonSMnZfZ7vAdt',
    'pop underground': 'KZazBEonSMnZfZ7vAdn',
    'post-grunge': 'KZazBEonSMnZfZ7vAdl',
    'post-punk': 'KZazBEonSMnZfZ7vA7v',
    'post-punk revival': 'KZazBEonSMnZfZ7vA7e',
    'post-rock/experimental': 'KZazBEonSMnZfZ7vA7d',
    'psychobilly': 'KZazBEonSMnZfZ7vA77',
    'queercore': 'KZazBEonSMnZfZ7vA7A',
    'riot grrrl': 'KZazBEonSMnZfZ7vA7k',
    'sadcore': 'KZazBEonSMnZfZ7vA76',
    'shoegaze': 'KZazBEonSMnZfZ7vA7F',
    'ska punk': 'KZazBEonSMnZfZ7vA71',
    'skatepunk': 'KZazBEonSMnZfZ7vA7J',
    'slowcore': 'KZazBEonSMnZfZ7vA7E',
    'space rock': 'KZazBEonSMnZfZ7vA7I',
    'third wave ska revival': 'KZazBEonSMnZfZ7vA7t',
    'twee pop': 'KZazBEonSMnZfZ7vA7n',
    'urban folk': 'KZazBEonSMnZfZ7vA7l'
}

export default Subgenres;